### PR TITLE
Bugfix: When setting the logger of the bot, we have to change the log…

### PR DESCRIPTION
**Pull request by iwalkalone69**
…ger of irc connection to take effect.

### CODE REVIEW

**Comment by elazar** [comment]
Can you update [this test](https://github.com/phergie/phergie-irc-bot-react/blob/ce94f71df696c7d379fcdd6c7b60aef73b8d8a78/tests/BotTest.php#L67-72) accordingly, please?

**Comment by iwalkalone69** [comment]
Test updated.

**Comment by elazar** [comment]
Note the comment above this test indicating that it's intended to be a unit test. Your change makes it rely on the behavior of the client dependency so that it becomes an integration test.

To correct this:

```php
$client = $this->getMockClient();
$this->bot->setClient($client);
$this->bot->setLogger($logger);
Phake::verify($client)->setLogger($logger);
```

This makes it a unit test again because it no longer relies on the behavior of the `setLogger()` and `getLogger()` methods of the client dependency, only verifies that `setLogger()` is called with the correct parameter.

**Comment by iwalkalone69** [comment]
Updated test.

**Comment by elazar** [comment]
@iwalkalone69 Sorry, I did not mean to imply that my example constituted the whole test. You've removed the assignment for `$logger`, which is still needed.

**Comment by enebe-nb** [comment]
Probably is this what elazar wants:
```php
    public function testSetLogger()
    {
        $client = $this->getMockClient();
        $logger = $this->getMockLogger();
        $this->bot->setClient($client);
        $this->bot->setLogger($logger);
        $this->assertSame($logger, $this->bot->getLogger());
        Phake::verify($client)->setLogger($logger);
    }
```

**Comment by elazar** [comment]
@enebe-nb Not sure @iwalkalone69 is still monitoring this issue. If you'd care to re-submit this PR with appropriate fixes, I'll be happy to merge it. :)

**Comment by iwalkalone69** [comment]
Sorry. I had to left this for a while because I had to focus on another thing. I will take care now.

**Comment by elazar** [comment]
@iwalkalone69 No worries, looks like @enebe-nb beat you to it. ;)

**Comment by iwalkalone69** [comment]
That's right! Thanks @elazar and @enebe-nb !

**Pull request closed without merging**
