### PR TITLE
Support evenement 2.0 and 3.0

### PR DESCRIPTION
**Pull request by WyriHaximus**
Evenement 3.0 has 99.9% the same API as 2.0 and provides a contains a nice performance improvement. I didn't see any cases where it would cause issues with Phergie so it should be good to go 🎉

### CODE REVIEW

**Comment by WyriHaximus** [comment]
ping @elazar @svpernova09 is there anything blocking this from getting merged (and preferably released)?

**Comment by elazar** [comment]
@WyriHaximus Is there anything we can do to fix the build failures?

**Comment by WyriHaximus** [comment]
@elazar I can look into those, but they seem unrelated to this PR so I'll be filing a new one

**Comment by WyriHaximus** [comment]
@elazar just filed #52 which should fix these errors

**Comment by WyriHaximus** [comment]
Rebased and squashed

**Comment by elazar** [comment]
👍

**Comment by svpernova09** [comment]
Thanks!

**Comment by WyriHaximus** [comment]
Awesome 🎉 . Any chance for a tag soon?

**Pull request merged**
